services:
  redis:
    image: redis:7-alpine
    container_name: bekal-redis
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bekal-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd' -Q 'SELECT 1' -C || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bekal-sqlserver-init
    restart: "no"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd
    volumes:
      - ./init-db.sh:/init-db.sh
      - ./script.sql:/script.sql
    entrypoint: ["/bin/bash", "/init-db.sh"]

  app:
    build: .
    container_name: bekal-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      sqlserver-init:
        condition: service_completed_successfully # waits for init to finish
