spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bekal;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.application.name=bekal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

app.security.jwt-secret=-oQ8lhn9GxURcICCEwGzzGedybSLCvdd2IoUuac5Yb8s
app.security.jwt-ttl-minutes=15m

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=uploads
spring.web.resources.static-locations=file:uploads/